// Auto-generated by Hermes Agent (flicker fix)
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:on_audio_query/on_audio_query.dart';
import 'package:spotiflac_android/providers/premium_playback_provider.dart';

class StaticArt extends ConsumerWidget {
  const StaticArt({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final current = ref.watch(premiumPlaybackProvider.select((p) => p.current));
    if (current == null) return const SizedBox.shrink();

    return RepaintBoundary(
      child: Stack(
        fit: StackFit.expand,
        children: [
          // Gradient Background (replaces missing background.png asset)
          Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
                colors: [Colors.black87, Colors.grey.shade900, Colors.black],
              ),
            ),
          ),
          // Blurred Cover Art Background
          if (current.coverPath != null && current.coverPath!.isNotEmpty)
            Positioned.fill(
              child: Hero(
                tag: 'now-art-${current.id}',
                child: QueryArtworkWidget(
                  key: ValueKey(current.id),
                  id: int.tryParse(current.id) ?? current.id.hashCode,
                  type: ArtworkType.AUDIO,
                  artworkFit: BoxFit.cover,
                  artworkQuality: FilterQuality.high,
                  keepOldArtwork: true,
                ),
              ),
            ),
          BackdropFilter(
            filter: ImageFilter.blur(sigmaX: 15, sigmaY: 15),
            child: Container(color: Colors.black.withOpacity(0.3)),
          ),
          // Large Cover Art (foreground)
          Center(
            child: Hero(
              tag: 'current_art',
              child: QueryArtworkWidget(
                key: ValueKey(current.id),
                id: int.tryParse(current.id) ?? current.id.hashCode,
                type: ArtworkType.AUDIO,
                artworkFit: BoxFit.contain,
                artworkQuality: FilterQuality.high,
                artworkBorder: BorderRadius.circular(12),
                nullArtworkWidget: const Icon(Icons.music_note, size: 200),
                keepOldArtwork: true,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
